commit

diff --git a/S3/bash-scripts/list-objects b/S3/bash-scripts/list-objects
--- a/S3/bash-scripts/list-objects
+++ b/S3/bash-scripts/list-objects
@@ -1,1 +1,17 @@
 #!/usr/bin/env bash
+echo ".. list objects"
+
+# Check for bucket name
+if [ -z "$1" ]; then
+  echo "Error: There need to be a bucket name provided."
+  exit 1
+fi
+
+BUCKET_NAME=$1
+REGION="us-east-1"
+
+aws s3api list-objects-v2 \
+--bucket $BUCKET_NAME 
+# --region "$REGION" \
+# --query Location \
+# --output text
